<?php
/**
 * A list of required PHP extensions autogenerated by the build script.
 *
 * @package SpeedSearch
 */

$required_extensions = [
    'curl',
    'dom',
    'json',
    'libxml',
    'mbstring',
    'pcre',
];
